name: Python CI Test

on:
  push:

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Scripts
        run: python app.py
