name: Conditionals

on:
  push:
  pull_request:

jobs:

  demo:

    runs-on: ubuntu-latest

    steps:

      - name: Only Main Branch

        if: github.ref == 'refs/heads/main'

        run: echo "Main Branch"

      - name: Intentional Failure

        run: exit 1

        continue-on-error: true

      - name: Run if Previous Failed

        if: failure()

        run: echo "Previous Step Failed"

  push-job:

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:

      - run: echo "Runs only on Push"
