name: External Trigger

on:
  repository_dispatch:
    types:
      - deploy-request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Payload
        run: |
          echo "Environment: ${{ github.event.client_payload.environment }}"
