name: Job Outputs

on:
  push:

jobs:

  generate:

    runs-on: ubuntu-latest

    outputs:
      today: ${{ steps.date.outputs.today }}

    steps:
      - id: date

        run: |
          echo "date=$(date)" >> $GITHUB_OUTPUT
  print:

    runs-on: ubuntu-latest
    needs: generate

    steps:
      - name: Print Output
        run: |
          echo "Today's Date"
          echo "${{ steps.date.output.today }}"
      
