name: GitHub Secrets Demo

on:
  push:

jobs:
  secrets-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Check if Secret Exists
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is set: false"
          fi

      - name: Use Secret as Environment Variable
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "Secret received successfully."
