name: Smart Trigger

on:
  push: 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint Successful"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test Successful"

  summary:
    runs-on: ubuntu-latest
    needs: 
      - lint
      - test
    steps:
      - name: Branch
        run: |
          if[[ "${{ github.ref_name }}" == "main" ]]

          then
            echo "This is main Brach"
          else
            echo "This is feature Branch"

      - name: Commit 
        run: |
          echo "${{ github.event.commits[0].message }}"
